version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt  # Install Python dependencies

  build:
    commands:
      - pytest tests/  # Run your Python tests (replace 'tests/' with the path to your test directory)

artifacts:
  files:
    - '**/*'  # Include all files and directories in the build context as artifacts
