version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt  # Install Python dependencies

artifacts:
  baseDirectory: GestureCam1  # Specify the directory containing built artifacts
  files:
    - 'app.py'  # Include only essential application files
    - 'index.html'
    - 'data/*.csv'  # Include data files if needed (replace with your data file pattern)
    - 'model.p'  # Include the model file (if needed)

