version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - mkdir -p dist  # Create the 'dist' directory if it doesn't exist
      - cp -r frontend/* dist/  # Copy frontend files to the 'dist' directory

artifacts:
  baseDirectory: GestureCam1  # Specify the base directory for artifacts
  files:
    - '**/*'
