version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - pip install -r requirements.txt

frontend:
  phases:
    build:
      commands:
        - echo "No frontend build required"

artifacts:
  files:
    - '**/*'
